spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  profiles:
    active: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
server:
  tomcat:
    uri-encoding: UTF-8